(("default" . ((user-emacs-directory . "~/.config/emacs.default/")))
 ("doom" . ((user-emacs-directory . "~/.config/emacs.doom")
            (env . (("DOOMDIR" . "~/.config/doom")))))
 ("lsp" . ((user-emacs-directory . "~/.config/emacs.lsp/")))
 ("slask" . ((user-emacs-directory . "~/.config/emacs.slask")))
 ("work" . ((user-emacs-directory . "~/.config/emacs.work")))
 ("rational" . ((user-emacs-directory . "~/.config/emacs.rational")
                (env . (("RATIONAL_EMACS_HOME" . "~/.config/rational"))))))
